version: '3.8'

services:
  web:
    container_name: eventos-web
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db
    networks:
      - eventos-net

  db:
    container_name: eventos-db
    image: mariadb:10.11
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventos
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1pa
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - eventos-net

  phpmyadmin:
    container_name: eventos-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: eventos-db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - eventos-net

networks:
  eventos-net:
    driver: bridge

volumes:
  db_data:
