services:
  web:
    build: .
    container_name: eventos-web
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
    depends_on:
      - maria.11

  maria.11:
    image: mariadb:10.11
    container_name: eventos-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventos
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: eventos-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: maria.11
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - maria.11

volumes:
  db_data:

